const main = require("./routes/admin/main");
const auth = require("./routes/admin/auth");
const dashboard = require("./routes/admin/dashboard");
const user = require("./routes/admin/user");
const aboutus = require("./routes/admin/aboutus");
const faq = require("./routes/admin/faq");
const privacypolicy = require("./routes/admin/privacypolicy");
const termscondition = require("./routes/admin/termscondition");
const contact = require("./routes/admin/contact");
const sliderRoute = require("./routes/admin/sliderRoute");
const delhiGame = require("./routes/admin/delhiGame");
const mumbaiGame = require("./routes/admin/mumbaiGame");
const starlineGame = require("./routes/admin/starlineGame");
const bid = require("./routes/admin/bid");
const result = require("./routes/admin/result");
const winning_history = require("./routes/admin/winning_history");
const settings = require("./routes/admin/settings");
const notice = require("./routes/admin/notice");
const support = require("./routes/admin/support");
const search = require("./routes/admin/search");
const product = require("./routes/admin/product");
const gameType = require("./routes/admin/gameType");
const payment = require("./routes/admin/payment");
const wallet = require("./routes/admin/wallet");

const AdminRoutes = (app) => {
  app.use("/", main);
  app.use("/admin", auth);
  app.use("/admin", dashboard);
  app.use("/admin/users", user);
  app.use("/admin", aboutus);
  app.use("/admin", faq);
  app.use("/admin", privacypolicy);
  app.use("/admin", termscondition);
  app.use("/admin/contact", contact);
  app.use("/admin/sliders", sliderRoute);
  app.use("/admin/delhi_game", delhiGame);
  app.use("/admin/mumbai_game", mumbaiGame);
  app.use("/admin/starline_game", starlineGame);
  app.use("/admin/bid", bid);
  app.use("/admin/result", result);
  app.use("/admin/winning", winning_history);
  app.use("/admin/settings", settings);
  app.use("/admin/notification", notice);
  app.use("/admin", support);
  app.use("/admin", search);
  app.use("/admin/product", product);
  app.use("/admin/gameType", gameType);
  app.use("/admin/payment_requests", payment);
  app.use("/admin/wallet", wallet);
};

module.exports = AdminRoutes;
